config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable, :openid_authenticatable, 
  devise :invitable, :database_authenticatable, :registerable,
         :confirmable, :lockable, :recoverable, :rememberable, 
         :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:vkontakte]
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # 
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
    end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
   def vkontakte
     # You need to implement the method below in your model (e.g. app/models/user.rb)
     @user = User.from_omniauth(request.env["omniauth.auth"])

     if @user.persisted?
       sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
       set_flash_message(:notice, :success, :kind => "Vkontakte") if is_navigational_format?
     else
       #session["devise.vkontakte_data"] = request.env["omniauth.auth"]
       #redirect_to new_user_registration_url
#       @user.save
       sign_in_and_redirect @user, :event => :authentication
       set_flash_message(:notice, :success, :kind => "Vkontakte") if is_navigational_format?
     end
   end

   def failure
      redirect_to root_path
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lab" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">/</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
              
            <% if current_user %>
                <li><%= link_to "Выход", destroy_user_session_path, :class => 'btn btn-small', :method => :delete %></li>
                <li><%= link_to "Профиль", "#", :class => 'btn btn-small' %></li>
                <li><%= link_to "Пригласить друга", new_user_invitation_path, :class => 'btn btn-small', :method => :get %></li>
            <% else %>
                <li><%= link_to "Войти", new_user_session_path, :class => 'btn btn-small', :method => :get %></li>
                <li><%= link_to "Vkontakte", user_vkontakte_omniauth_authorize_path %></li>
                <li><%= link_to "Зарегистрироваться", new_user_registration_path, :class => 'btn btn-small', :method => :get %></li>
            <% end %>
            
                <li><%= link_to "Администрировать", admin_root_path, :class => 'btn btn-small', :method => :get %></li>  
              
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      
      
<hr>
      <footer>
        <p>&copy; Nagaev is waching over you, 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <% if f.object.class.require_password_on_accepting %>
  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>
  <% end %>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => user_invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>

app/views/welcome/index.html.erb
<h1>
    <% if current_user %>
      <%=  "Добро пожаловать, #{current_user.email}!" %>
    <% else %>
      <%=  "Добро пожаловать!" %>
    <% end  %>
</h1>
    <% if current_user %>
<p>На этой странице планируется отображать карту проекта и важнейшие новости. Но, поскольку проект находится в начальной стадии, то тут пока ничего нет.</p>
<p>В настоящий момент вы можете отредактировать свой профиль, сменить пароль и пригласить новых пользователей.</p>
    <% else %>
<p>Вы находитесь на сертификационном сервере проекта ctrl-p.center</p>
<p>Сервер обеспечивает аутентификацию пользователей любых ресурсов распределенной терминальной среды исполнения заказов.</p>
<p>Проект открыт для новых пользователей. Пожалуйста, регистрируйтесь.</p>
    <% end  %>